"""add_levels_and_categories

Revision ID: 6b8b540900c7
Revises: 842ed278c06d
Create Date: 2026-01-09 14:38:06.100762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8b540900c7'
down_revision: Union[str, None] = '842ed278c06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('order')
    )
    op.create_index(op.f('ix_word_categories_id'), 'word_categories', ['id'], unique=False)
    op.create_table('word_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('order')
    )
    op.create_index(op.f('ix_word_levels_id'), 'word_levels', ['id'], unique=False)

    # --- Seed Data Start ---
    op.bulk_insert(sa.table('word_levels',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('label', sa.String, nullable=False),
        sa.Column('order', sa.Integer, nullable=False)
    ), [
        {'id': 1, 'label': 'A1.1', 'order': 1}
    ])

    op.bulk_insert(sa.table('word_categories',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('label', sa.String, nullable=False),
        sa.Column('order', sa.Integer, nullable=False)
    ), [
        {'id': 1, 'label': 'Function Words', 'order': 1}
    ])
    # --- Seed Data End ---

    op.add_column('users', sa.Column('current_level_id', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('current_category_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'users', 'word_levels', ['current_level_id'], ['id'])
    op.create_foreign_key(None, 'users', 'word_categories', ['current_category_id'], ['id'])
    op.add_column('words', sa.Column('level_id', sa.Integer(), nullable=True))
    op.add_column('words', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'words', 'word_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'words', 'word_levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_column('words', 'category_id')
    op.drop_column('words', 'level_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_category_id')
    op.drop_column('users', 'current_level_id')
    op.drop_index(op.f('ix_word_levels_id'), table_name='word_levels')
    op.drop_table('word_levels')
    op.drop_index(op.f('ix_word_categories_id'), table_name='word_categories')
    op.drop_table('word_categories')
    # ### end Alembic commands ###
