"""make_user_level_category_nullable

Revision ID: 955c1c3d8b57
Revises: 6b8b540900c7
Create Date: 2026-01-09 16:37:03.637459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955c1c3d8b57'
down_revision: Union[str, None] = '6b8b540900c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'current_level_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None)
    op.alter_column('users', 'current_category_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'current_category_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'current_level_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###
