"""add_auth_fields_to_users

Revision ID: e93a64b3bb48
Revises: 955c1c3d8b57
Create Date: 2026-01-12 13:50:15.311136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93a64b3bb48'
down_revision: Union[str, None] = '955c1c3d8b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add columns as nullable first
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))

    # Step 2: Set default values for existing users
    # Use username@legacy.local as temporary email
    # Use an invalid hash that cannot be verified
    op.execute("""
        UPDATE users
        SET email = username || '@legacy.local',
            hashed_password = 'LEGACY_USER_NEEDS_PASSWORD_RESET',
            is_active = true
        WHERE email IS NULL
    """)

    # Step 3: Make columns non-nullable
    op.alter_column('users', 'email', nullable=False)
    op.alter_column('users', 'hashed_password', nullable=False)
    op.alter_column('users', 'is_active', nullable=False)

    # Step 4: Create unique index on email
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
